In [ ]:
#importing the packages
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb
import numpy as np

sb.set()

In [ ]:
#reading the dataset
analysis = pd.read_csv('/kaggle/input/matches/dataset.csv')

In [ ]:
analysis

In [ ]:
#dropping the unnecessary columns from the dataset
analysis = analysis.drop(['umpire1'], axis=1)
analysis = analysis.drop(['umpire2'], axis=1)
analysis = analysis.drop(['umpire3'], axis=1)
analysis = analysis.drop(['dl_applied'], axis=1)

In [ ]:
#This code will give you total number of null values in each features in the data frame.
analysis.isnull().sum()

In [ ]:
#Dropping the null values in each column
analysis = analysis.dropna(axis=0)

In [ ]:
#This code will give you total number of null values in each features in the data frame.
analysis.isnull().sum()

In [ ]:
analysis

In [ ]:
#This code will return the details of the players with POTM awards in descending order.
analysis['player_of_match'].value_counts()[:10]

In [ ]:
#Data Visualisation with barplot. This code visualises who won the maximum POTM awards from the dataset.
sb.barplot(x = analysis['player_of_match'].value_counts()[:10].index, y = analysis['player_of_match'].value_counts()[:10])
plt.xticks(rotation = 60)

In [ ]:
#This code will return the number of unique values from player_of_match column.
analysis['player_of_match'].nunique()

In [ ]:
#Data Visualisation with heatmap
sb.heatmap(analysis.corr(), annot=True)

In [ ]:
#This code will return the count of toss won by each team.
analysis['toss_winner'].value_counts()

In [ ]:
#Data Visualisation with lineplot. This code visualises which team has highest toss winning streak from the dataset.
plt.figure(figsize = (10,7))
sb.lineplot(x = analysis['toss_winner'].value_counts().index, y = analysis['toss_winner'].value_counts())
plt.xticks(rotation = 90)
plt.show()

In [ ]:
#This code will return the number of matches won by each team.
analysis['winner'].value_counts()

In [ ]:
#Data Visualisation with scatterplot. This code visualises which team has highest winning streak from the dataset.
plt.figure(figsize = (15,7))
sb.scatterplot(x = analysis['winner'].value_counts().index, y = analysis['winner'].value_counts())
plt.xticks(rotation = 90)
plt.show()

In [ ]:
#This code will return the maximum value from the dataset
analysis['id'].max()

In [ ]:
#This code will return the number of unique values from season column.
analysis['season'].nunique()

In [ ]:
#This code will return how many seasons have been played from the dataset.
analysis['season'].unique()

In [ ]:
#This code will return the length of the above array
len(analysis['season'].unique())

In [ ]:
#The variable bowl_first_win stores who bowled first and won the match from the given data.
bowl_first_win = analysis[analysis['win_by_wickets']>=1]

In [ ]:
#This code will return the data of the team who bowled first and won the match.
bowl_first_win

In [ ]:
#The variable bat_first_win stores who bowled second and won the match from the given data.
bat_first_win = analysis[analysis['win_by_runs']>0]

In [ ]:
#This code will return the data of the team who bowled second and won the match.
bat_first_win

In [ ]:
#This code visualises the number of matches played in each season from 2008 to 2019.
sb.countplot(x='season', data=analysis)

In [ ]:
#This code will return the details of the team that has won the match by maximum runs.
analysis.iloc[bat_first_win['win_by_runs'].idxmax()]

In [ ]:
#This code will return the details of the team that has won the match by minimum runs.
analysis.iloc[bat_first_win['win_by_runs'].idxmin()]

In [ ]:
#This code will return the details of the team that has won the match by minimum wickets.
analysis.iloc[bowl_first_win['win_by_wickets'].idxmin()]

In [ ]:
#This code will return the details of the team that has won the match by maximum wickets.
analysis.iloc[bowl_first_win['win_by_wickets'].idxmax()]

In [ ]:
bat_first_win['win_by_runs'].max()

In [ ]:
bat_first_win['win_by_runs'].min()

In [ ]:
bowl_first_win['win_by_wickets'].max()

In [ ]:
bowl_first_win['win_by_wickets'].min()

In [ ]:
#This code will return the data(in an ascending order) of the team that has bowled first and won the match.
bowl_first_win.sort_values(by='win_by_wickets')

In [ ]:
#This code will return the data(in an ascending order) of the team that has bowled second and won the match.
bat_first_win.sort_values(by='win_by_runs')